language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

before_script:
  - psql -c 'CREATE DATABASE gazette_testing;' -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres

install:
  - composer install --prefer-source --no-interaction
  - npm install -g bower
  - bower install

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

script: vendor/bin/phpunit
